name: Build QRB ROS packages on Ubuntu

on:
    push:
    pull_request:

env:
    ROS_WS: ${{ github.workspace }}/ros2_ws/
    ROS_SRC: ${{ github.workspace }}/ros2_ws/src

jobs:
  ros-build:
    uses: ./.github/workflows/ubuntu-build-call.yml
    with:
      # QRB ROS dependency
      dependencies: "qualcomm-qrb-ros/qrb_ros_transport qualcomm-qrb-ros/lib_mem_dmabuf"